build:
    image: crossdev/package-builder
    commands:
        - chown -R builder:builder .
        - sudo -u builder yaourt --noconfirm -Sy bats-git
        - sudo -u builder makepkg -s --noconfirm
        - mkdir output
        - mv *.tar.xz output/
        - cd output
        - repo-add build.db.tar.gz *.tar.xz
        - unlink build.db
        - tar xvf build.db.tar.gz
        - rm build.db.tar.gz

publish:
    s3:
        acl: public-read
        region: "eu-west-1"
        bucket: "crossdev"
        access_key: $$ACCESS_KEY
        secret_key: $$SECRET_KEY
        source: output
        target: /tools/os/any/
        recursive: true
